### ISSUE TITLE
Identical geometry points

### ISSUE THREAD

**Issue by rabazyo** [rabazyo/AirBnb-Spatial-project#5]
Problem with geometrical point. At this point they are simply removed however this will affect the results. When they are not removed they conflict in the Rao's score and further spatial autoreggresive models. File used in the code is barcelona weekdays from data sets file.
@rsbivand #4

**Comment by rsbivand** [comment]
Please include the specific error messages and where in the notebook they occur.

**Comment by rsbivand** [comment]
The problem arises when `k` is less than the number of properties at the same location given the precision of the coordinates. So:
```
> bar_sf|> knearneigh(k=5) -> a
Warning in rbind(c(196L, 808L, 818L, 822L, 862L), c(368L, 815L, 888L, 1157L,  :
  number of columns of result is not a multiple of vector length (arg 1)
> bar_sf|> knearneigh(k=6) -> a
Warning in rbind(c(19L, 196L, 808L, 818L, 822L, 862L), c(368L, 686L, 815L,  :
  number of columns of result is not a multiple of vector length (arg 1)
> bar_sf|> knearneigh(k=7) -> a
> knn2nb(a)
Neighbour list object:
Number of regions: 1555 
Number of nonzero links: 10885 
Percentage nonzero weights: 0.4501608 
Average number of links: 7 
Non-symmetric neighbours list
> (bar_sf|> knearneigh(k=7) |>
+  knn2nb(row.names=bar_sf$X) -> bar_nb)
Neighbour list object:
Number of regions: 1555 
Number of nonzero links: 10885 
Percentage nonzero weights: 0.4501608 
Average number of links: 7 
Non-symmetric neighbours list
```
No need to drop duplicated locations, but increase `k` to the count of identical locations. Use `options("warn"=1)` and `debug(knearneigh)` to step through the function to find the problem. I'll add a more informative warning.

**Comment by rabazyo** [comment]
@rsbivand  After increasing k to 7 the problem still exists. Even if it is set at very high number problem still occur.

```r
> #Creating neighbouring object
>  (bar_sf|> knearneigh(k=7) |>
+ knn2nb(row.names=bar_sf$...1) -> bar_nb)
Ostrzeżenie: knearneigh: identical points foundOstrzeżenie: knearneigh: kd_tree not available for identical pointsNeighbour list object:
Number of regions: 1555 
Number of nonzero links: 10885 
Percentage nonzero weights: 0.4501608 
Average number of links: 7 
Non-symmetric neighbours list
```

**Comment by rsbivand** [comment]
No, you need to install 1.3-4 from github to supress the spurious warnings that do not apply to your case - `remotes::install_github("r-spatial/spdep")`. If you cannot install a source package (you need on Windows Rtools installed for your version of R to install from source), put `suppressWarnings()` around `knearneigh`. Alternatively, try: `install.packages("spdep", repos="https://r-spatial.r-universe.dev")` - untried.

**Comment by rabazyo** [comment]
i have installed the rtools and after that i receive this message:
```r
> remotes::install_github("r-spatial/spdep")
Using GitHub PAT from the git credential store.
BŁĄD: Failed to install 'spdep' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 58/60
  Rate limit reset at: 2024-04-29 20:55:30 UTC
```

**Comment by rabazyo** [comment]
@rsbivand  
With the second method i receive this:
```r
pakiet ‘spdep’ został pomyślnie rozpakowany oraz sumy MD5 zostały sprawdzone
Warning in install.packages :
  nie można usunąć poprzedniej instalacji pakietu ‘spdep’
Warning in install.packages :
  problem z kopiowaniem C:\Users\facem\AppData\Local\R\win-library\4.3\00LOCK\spdep\libs\x64\spdep.dll do C:\Users\facem\AppData\Local\R\win-library\4.3\spdep\libs\x64\spdep.dll: Permission denied
Warning in install.packages :
  przywrócono ‘spdep’

Pobrane pakiety binarne są w
	C:\Users\facem\AppData\Local\Temp\RtmpcpyPwc\downloaded_packages
```

**Comment by rsbivand** [comment]
In both cases, install always outside Rstudio, and always in a new R session. In the second case, the user directory is not writeable, in the first case probably Rstudio has got in the way - it sets stuff without telling the user.
